name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4 
    - name: Test
      run: cargo test --verbose
  
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4 
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Check formatting
      run: cargo fmt --check

  audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4 
    - name: Audit
      run: cargo audit