name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose 
    - name: Lint
      run: |
        cargo fmt --check
        cargo clippy -- -D warnings
    - name: Audit
      run: cargo audit